### ISSUE TITLE
Remove dependence on Polymer

### ISSUE THREAD

**Issue by rnicholus** [rnicholus/file-input#24]
Similar to ajax-form, I don't believe file-input benefits much from Polymer. In fact, it makes maintenance more complicated, IMHO. This was discussed a bit more at rnicholus/ajax-form#55.

**Comment by eximius313** [comment]
When do you plan to finish?

**Comment by rnicholus** [comment]
Shortly after I start.

**Comment by rnicholus** [comment]
With some of the recent breaking changes to the Shadow DOM spec, and the fact that moving away from polymer requires a lot more code in the case of `<file-input>`, I'm wondering if it's worth the effort to go this route at the moment. My ajax-form element was pretty easy to decouple from polymer. Also, unit tests still need to be rewritten.

**Comment by rnicholus** [comment]
I'm not sure it makes sense to do this, given what Polymer provides. A fair amount of boilerplate code would have to be introduced. I think the best choice is to update file-input to work with Polymer 1.x instead.

**Comment by eximius313** [comment]
Good for me. 
And could you please provide some date when do you plan to migrate to 1.0 (more or less) ?

**Comment by rnicholus** [comment]
No, sorry.
