### ISSUE TITLE
Remove dependence on Polymer

### ISSUE THREAD

**Issue by rnicholus** [rnicholus/file-input#26]
It doesn't seem to be worthwhile to divorce file-input from Polymer (like I did with ajax-form), so the next best thing is to make it Polymer 1.x-friendly. There were some breaking changes in 1.x, but I imagine this will not be too difficult to pull off. Pre-release testing with the current version of ajax-form required.

**Comment by jonbonraki** [comment]
is there any update on moving file input to polymer 1.0 friendly.

thanks

**Comment by rnicholus** [comment]
I expect to complete this sometime next week.

**Comment by rnicholus** [comment]
@chris-l didn't you already complete this in a fork of yours?

**Comment by chris-l** [comment]
Update to Polymer 1.0? No, I didn't.

What I did was a [version of file-input that does not require Polymer at all.](https://github.com/chris-l/file-input/commits/master)

However, I see that @camelCaseD did a [version updated to Polymer 1.0](https://github.com/camelCaseD/file-input/commits/master).

I haven't tested that one (yet).

**Comment by camelCaseD** [comment]
If you want to merge my changes for the upgrade to polymer 1.0? I'd be happy to do that. But the only issue is wether you want to include my onClick handler changes I made from the commit before the upgrade.

Also is there an easy way to test and make sure that the changes I made in the upgrade work properly?

**Comment by rnicholus** [comment]
>is there an easy way to test and make sure that the changes I made in the upgrade work properly
There are [some unit tests](https://github.com/rnicholus/file-input/blob/master/test/unit/file-input-spec.js) that should be passing. Adjustments may need to be made to ensure tests are passing. If you open up a PR, I can look into fixing these if they are broken.

To be honest, I'm fine using whichever version is easiest to get unit tests passing - @camelCaseD's Polymer 1.0 version of @chris-l's no-polymer version.

**Comment by rnicholus** [comment]
Starting work on this in the [polymer-1.x branch](https://github.com/rnicholus/file-input/tree/polymer-1.x).

**Comment by rnicholus** [comment]
OMFG. Only made it about 30 pages into the Polymer 1.x migration guide before I gave up. I'm going to pull in @chris-l's dependency-free version after all and work to fix the tests.

**Comment by rnicholus** [comment]
I'm making  good progress, and the tests I've rewritten are passing locally, but they are all failing on travis-ci. Not sure why - same browser (FF 40) same version of node (0.10.40). I'll have to look into this further.

**Comment by rnicholus** [comment]
Fixed! I'll continue on rewriting the tests and any bugs I find along the way. Afterwards, Polymer-free file-input will be bumped to 2.0.0.

**Comment by rnicholus** [comment]
Done - 2.0.0. https://github.com/rnicholus/file-input/releases/tag/2.0.0
