### ISSUE TITLE
Polymer 0.5 dependency left in index.html

### ISSUE THREAD

**Issue by eximius313** [rnicholus/file-input#27]
After invoking `bower install --save "file-input#^2.0"` there is an `file-input/index.html` which contains references to the old Polymer:

```
  <script src="../webcomponentsjs/webcomponents.js"></script>
  <link rel="import" href="../polymer/polymer.html">
  <link rel="import" href="../core-component-page/core-component-page.html">
```

**Comment by rnicholus** [comment]
This is needed to render the documentation page. You will see that the library itself does not use polymer. I have no plans to upgrade the docs to use a later version of polymer or to not use polymer.
