### ISSUE TITLE
How to style the "<file-input>" as a Polymer "<paper-button>" style

### ISSUE THREAD

**Issue by edouardmercier** [rnicholus/file-input#33]
First of all, congratulations for your work.

I'm currently using the `file-input` in a Polymer 1.x application. However, I would like the rendering to look like a regular `paper-button`. On that purpose, I have inserted set the following code:

```
<file-input id="fileChooser" accept="image/*" extensions='["jpeg", "jpg", "png", "webp", "gif"]' max-files="1">
  <paper-button raised>Pick a file</paper-button>
</file-input>
```

but when clicking on the top edges of the button, the latter seems to capture the `on-tap` event.

Could you provide some short documentation on how to integrate properly this component with a Polymer `paper-button` element, please?

**Comment by rnicholus** [comment]
Sorry, I'm not familiar w/ Polymer (anymore).

**Comment by rnicholus** [comment]
This whole thing really needs to be rewritten to support the latest iteration of the custom elements spec as well. Integrating with any particular library is not important to me.
